image: node:16.1.0-alpine3.13

stages:
  - test
  - deploy

cache:
  paths:
    - node_modules/

before_script:
  - npm install -g @quasar/cli
  - npm install

test:
  stage: test
  script:
    - quasar build

pages:
  stage: deploy
  script:
    - quasar build
    - mv -R dist/spa public
  artifacts:
    paths:
      - public
  only:
    - master
