image: node:16.1.0-alpine3.13

stages:
  - test
  - deploy

cache:
  paths:
    - node_modules/

before_script:
  - npm install -g @quasar/cli
  - npm install
  - rm -Rf dist

test:
  stage: test
  script:
    - quasar build

pages:
  stage: deploy
  script:
    - quasar build
    - rm -Rf public && mkdir public
    - cp -Rf dist/spa/* public/
    - find public -type f -regex '.*\.\(htm\|html\|txt\|text\|js\|css\)$' -exec gzip -f -k {} \;
  artifacts:
    paths:
      - public
  only:
    - master
