stages:
  - test
  - fetch-version
  - deploy

variables:
  project_name: $CI_PROJECT_NAME
  SEMANTIC_RELEASE_PACKAGE: $CI_PROJECT_NAME
  DOCKER_HOST: tcp://docker:2375/

test quasar:
  image: node:16.1.0-alpine3.13
  stage: test
  cache:
    paths:
      - node_modules/
  before_script:
    - npm install -g @quasar/cli
    - npm install
    - rm -Rf dist
  script:
    - quasar build

test docker:
  stage: test
  image: registry.griefed.de/prosper/docker-with-buildx:latest
  variables:
    DOCKER_HOST: tcp://docker:2375/
  services:
    - docker:dind
  before_script:
    - docker login -u "$DOCKERHUB_USER" -p "$DOCKERHUB_TOKEN" docker.io
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
    - docker buildx create --driver docker-container --use
  script:
    - docker buildx build
      --push
      --platform linux/amd64,linux/arm/v7,linux/arm64
      --cache-from "$CI_REGISTRY_IMAGE:develop"
      --tag "$CI_REGISTRY_IMAGE:develop"
      --tag "index.docker.io/$DOCKERHUB_USER/$DOCKERHUB_REPO:develop" .

pages:
  needs: ['test quasar']
  image: node:16.1.0-alpine3.13
  stage: deploy
  cache:
    paths:
      - node_modules/
  before_script:
    - npm install -g @quasar/cli
    - npm install
    - rm -Rf dist
  script:
    - quasar build
    - cp -Rf dist/spa/* public/
  artifacts:
    paths:
      - public
    expire_in: 1 week

release:
  image: registry.griefed.de/prosper/gitlab-semantic-release:latest
  stage: fetch-version
  only:
    refs:
      - master
      - main
  script:
    - npx semantic-release
  artifacts:
    paths:
      - VERSION.txt


dockerhub:
  needs: ['release']
  stage: deploy
  image: registry.griefed.de/prosper/docker-with-buildx:latest
  variables:
    DOCKER_HOST: tcp://docker:2375/
  services:
    - docker:dind
  artifacts:
    paths:
      - VERSION.txt
  before_script:
    - VERSION=$(cat VERSION.txt)
    - docker login -u "$DOCKERHUB_USER" -p "$DOCKERHUB_TOKEN" docker.io
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
    - docker buildx create --driver docker-container --use
  script:
    - docker buildx build
      --push
      --platform linux/amd64,linux/arm/v7,linux/arm64
      --cache-from "$CI_REGISTRY_IMAGE:develop"
      --tag "$CI_REGISTRY_IMAGE:latest"
      --tag "$CI_REGISTRY_IMAGE:$CI_COMMIT_TAG"
      --tag "index.docker.io/$DOCKERHUB_USERNAME/$DOCKERHUB_REPO:latest"
      --tag "index.docker.io/$DOCKERHUB_USERNAME/$DOCKERHUB_REPO:$CI_COMMIT_TAG" .
  only:
    refs:
      - tags
